apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-utsv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0030-tenant/tkwch-fix-0075-0030-app/devfile-sample-utsv@sha256:edcdefd9966462b84cd7576900066ae42e05ed5c57362e5c967919275cdc60cf
        name: my-nodejs
        resources: {}
status: {}
